// <auto-generated />
using Database_Romanzi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database_Romanzi.Migrations
{
    [DbContext(typeof(RomanziContext))]
    [Migration("20251105213219_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Database_Romanzi.Data.Autore", b =>
                {
                    b.Property<int>("AutoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazionalita")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AutoreId");

                    b.ToTable("Autori");
                });

            modelBuilder.Entity("Database_Romanzi.Data.Personaggio", b =>
                {
                    b.Property<int>("PersonaggioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RomanzoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sesso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonaggioId");

                    b.HasIndex("RomanzoId");

                    b.ToTable("Personaggi");
                });

            modelBuilder.Entity("Database_Romanzi.Data.Romanzo", b =>
                {
                    b.Property<int>("RomanzoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnnoPubblicazione")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RomanzoId");

                    b.HasIndex("AutoreId");

                    b.ToTable("Romanzi");
                });

            modelBuilder.Entity("Database_Romanzi.Data.Personaggio", b =>
                {
                    b.HasOne("Database_Romanzi.Data.Romanzo", "Romanzo")
                        .WithMany()
                        .HasForeignKey("RomanzoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Romanzo");
                });

            modelBuilder.Entity("Database_Romanzi.Data.Romanzo", b =>
                {
                    b.HasOne("Database_Romanzi.Data.Autore", "Autore")
                        .WithMany()
                        .HasForeignKey("AutoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autore");
                });
#pragma warning restore 612, 618
        }
    }
}
