// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtilizziComputer3.Model;

#nullable disable

namespace UtilizziComputer3.Migrations
{
    [DbContext(typeof(UtilizziContext))]
    partial class UtilizziContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("UtilizziComputer3.Data.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Classe");
                });

            modelBuilder.Entity("UtilizziComputer3.Data.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Collocazione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modello")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Computer");
                });

            modelBuilder.Entity("UtilizziComputer3.Data.Studente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClasseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("UtilizziComputer3.Data.Utilizza", b =>
                {
                    b.Property<int>("StudenteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataOraInizioUtilizzo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataOraFineUtilizzo")
                        .HasColumnType("TEXT");

                    b.HasKey("StudenteId", "ComputerId", "DataOraInizioUtilizzo");

                    b.HasIndex("ComputerId");

                    b.ToTable("Utilizza");
                });

            modelBuilder.Entity("UtilizziComputer3.Data.Studente", b =>
                {
                    b.HasOne("UtilizziComputer3.Data.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("UtilizziComputer3.Data.Utilizza", b =>
                {
                    b.HasOne("UtilizziComputer3.Data.Computer", "Computer")
                        .WithMany("Utilizzi")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtilizziComputer3.Data.Studente", "Studente")
                        .WithMany("Utilizzi")
                        .HasForeignKey("StudenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("Studente");
                });

            modelBuilder.Entity("UtilizziComputer3.Data.Computer", b =>
                {
                    b.Navigation("Utilizzi");
                });

            modelBuilder.Entity("UtilizziComputer3.Data.Studente", b =>
                {
                    b.Navigation("Utilizzi");
                });
#pragma warning restore 612, 618
        }
    }
}
