// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtilizziComputer.Model;

#nullable disable

namespace UtilizziComputer.Migrations
{
    [DbContext(typeof(UtilizziContext))]
    [Migration("20251111082443_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("UtilizziComputer.Data.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classi");
                });

            modelBuilder.Entity("UtilizziComputer.Data.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Collocazione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modello")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Computer");
                });

            modelBuilder.Entity("UtilizziComputer.Data.Studente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClasseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.ToTable("Studente");
                });

            modelBuilder.Entity("UtilizziComputer.Data.Utilizza", b =>
                {
                    b.Property<int>("StudenteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataOraInizioUtilizzo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataOraFineUtilizzo")
                        .HasColumnType("TEXT");

                    b.HasKey("StudenteId", "ComputerId", "DataOraInizioUtilizzo");

                    b.HasIndex("ComputerId");

                    b.ToTable("Utilizzi");
                });

            modelBuilder.Entity("UtilizziComputer.Data.Studente", b =>
                {
                    b.HasOne("UtilizziComputer.Data.Classe", "Classe")
                        .WithMany("Studenti")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("UtilizziComputer.Data.Utilizza", b =>
                {
                    b.HasOne("UtilizziComputer.Data.Computer", "Computer")
                        .WithMany("Utilizzi")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtilizziComputer.Data.Studente", "Studente")
                        .WithMany("Utilizzi")
                        .HasForeignKey("StudenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("Studente");
                });

            modelBuilder.Entity("UtilizziComputer.Data.Classe", b =>
                {
                    b.Navigation("Studenti");
                });

            modelBuilder.Entity("UtilizziComputer.Data.Computer", b =>
                {
                    b.Navigation("Utilizzi");
                });

            modelBuilder.Entity("UtilizziComputer.Data.Studente", b =>
                {
                    b.Navigation("Utilizzi");
                });
#pragma warning restore 612, 618
        }
    }
}
